### ISSUE TITLE
Could not infer channel numbers

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#185]
Trying to import recordings for a new year in a fresh archive. When I tried to import recordings, I got the following error: "Could not infer recorder channel numbers for recording file "MSGR_2021-04-01_00.53.00_Z.wav"." I removed that file, and got it for the next one. Any ideas?

**Comment by HaroldMills** [comment]
That error message probably means that the number of microphone-to-recorder connections specified for your station at the time of your recording differs from the number of channels in the recording, so that Vesper can't be sure how to associate microphones with recording channels. How many microphone connections are there, and how many channels in the recording?

**Comment by RichardLitt** [comment]
Just two station devices - a mic (Oldbird) and a recorder (PC). 

```
station_devices:

    - station: MSGR
      start_time: 2020-01-01
      end_time: 2022-01-01
      devices:
          - PC
          - 21c
      connections:
          - output: 21c Output
            input: PC Input 0
```

How can I check how many channels are in a recording?
